# Generated by Django 6.0 on 2025-12-24 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(help_text='Ex: un, metro, litro, etc', max_length=20)),
                ('ultimo_preco_unitario', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10, verbose_name='Preço Atual (Unitário)')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('gramatura', models.CharField(max_length=20)),
                ('formato', models.CharField(max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('ultimo_preco_unitario', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10, verbose_name='Preço Atual (Unitário)')),
            ],
            options={
                'verbose_name': 'Catálogo de Papel',
                'verbose_name_plural': 'Catálogo de Papéis',
                'ordering': ['nome', 'gramatura'],
            },
        ),
        migrations.CreateModel(
            name='CompraPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField()),
                ('fornecedor', models.CharField(max_length=100)),
                ('qtd_embalagem', models.IntegerField(verbose_name='Qtd. no Pacote')),
                ('valor_pacote', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago (Pacote)')),
                ('valor_unitario', models.DecimalField(decimal_places=4, editable=False, max_digits=10)),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='materiais.papel')),
            ],
            options={
                'verbose_name': 'Entrada de Estoque',
                'verbose_name_plural': 'Histórico de Compras',
                'ordering': ['-data_compra'],
            },
        ),
    ]
