# Generated by Django 6.0 on 2025-12-26 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAcabamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(choices=[('red', 'Vermelho'), ('orange', 'Laranja'), ('amber', 'Amarelo'), ('green', 'Verde'), ('teal', 'Verde Água'), ('blue', 'Azul'), ('indigo', 'Indigo'), ('purple', 'Roxo'), ('pink', 'Rosa'), ('gray', 'Cinza')], default='blue', max_length=20)),
            ],
            options={
                'verbose_name': 'Config: Categ. de Acabamento',
                'verbose_name_plural': 'Config: Tags de Acabamentos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(choices=[('red', 'Vermelho'), ('orange', 'Laranja'), ('amber', 'Amarelo'), ('green', 'Verde'), ('teal', 'Verde Água'), ('blue', 'Azul'), ('indigo', 'Indigo'), ('purple', 'Roxo'), ('pink', 'Rosa'), ('gray', 'Cinza')], default='gray', max_length=20)),
            ],
            options={
                'verbose_name': 'Config: Categ. de Insumo',
                'verbose_name_plural': 'Config: Tags de Insumos',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100, verbose_name='Razão Social / Nome')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='Pessoa de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('segmento', models.CharField(choices=[('PAPEL', 'Papéis e Adesivos'), ('INSUMO', 'Insumos e Acabamentos'), ('IMPRESSORA', 'Tonners e Suprimentos')], default='PAPEL', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Cadastros: Fornecedores',
                'ordering': ['nome_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Couchê, Offset, Adesivo', max_length=100)),
                ('gramatura', models.CharField(help_text='Ex: 90g, 150g', max_length=20)),
                ('tipo', models.CharField(blank=True, help_text='Ex: Fosco, Brilho', max_length=50, null=True)),
                ('largura_mm', models.IntegerField(help_text='Ex: 330', verbose_name='Largura (mm)')),
                ('altura_mm', models.IntegerField(help_text='Ex: 480', verbose_name='Altura (mm)')),
                ('estoque_atual', models.IntegerField(default=0, editable=False, verbose_name='Estoque (Pcts)')),
                ('ultimo_valor_pacote', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Último Pago (Pacote)')),
                ('ultimo_preco_unitario', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10, verbose_name='Preço Atual (Folha)')),
            ],
            options={
                'verbose_name': 'Catálogo: Papel',
                'verbose_name_plural': 'Catálogo: Papéis',
                'ordering': ['nome', 'gramatura'],
            },
        ),
        migrations.CreateModel(
            name='Acabamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Encadernação Wire-o A4, Refile, Vinco', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Detalhes técnicos do serviço')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.categoriaacabamento', verbose_name='Tag / Categoria')),
            ],
            options={
                'verbose_name': 'Serviço: Acabamento',
                'verbose_name_plural': 'Serviço: Acabamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Espiral 12mm, Capa PP, Cola Hotmelt', max_length=100)),
                ('unidade_medida', models.CharField(default='unid', help_text='Ex: kg, litro, caixa, milheiro', max_length=20)),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque Atual')),
                ('ultimo_preco_custo', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10, verbose_name='Último Custo (Unitário)')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.categoriainsumo', verbose_name='Tag / Categoria')),
            ],
            options={
                'verbose_name': 'Catálogo: Insumo',
                'verbose_name_plural': 'Catálogo: Insumos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField()),
                ('qtd_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Comprada')),
                ('valor_total_nota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total da Nota')),
                ('valor_unitario', models.DecimalField(decimal_places=4, editable=False, max_digits=10, verbose_name='Custo Unitário')),
                ('fornecedor', models.ForeignKey(limit_choices_to={'segmento__in': ['INSUMO']}, on_delete=django.db.models.deletion.PROTECT, to='materiais.fornecedor')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='materiais.insumo')),
            ],
            options={
                'verbose_name': 'Movimento: Compra de Insumo',
                'verbose_name_plural': 'Movimento: Compras de Insumo',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='CompraPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField()),
                ('qtd_pacotes_compra', models.IntegerField(default=1, verbose_name='Qtd. Pacotes')),
                ('qtd_embalagem', models.IntegerField(verbose_name='Folhas por Pacote')),
                ('valor_pacote', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Pacote')),
                ('valor_unitario', models.DecimalField(decimal_places=4, editable=False, max_digits=10)),
                ('fornecedor', models.ForeignKey(limit_choices_to={'segmento__in': ['PAPEL']}, on_delete=django.db.models.deletion.PROTECT, to='materiais.fornecedor')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='materiais.papel')),
            ],
            options={
                'verbose_name': 'Movimento: Compra de Papel',
                'verbose_name_plural': 'Movimento: Compras de Papel',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('qtd_pacotes_baixa', models.IntegerField(verbose_name='Qtd. Pacotes Usados')),
                ('observacao', models.CharField(blank=True, max_length=100, verbose_name='Motivo/Obs')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='materiais.papel')),
                ('usuario', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento: Baixa',
                'verbose_name_plural': 'Movimento: Baixas / Uso Interno',
                'ordering': ['-data_movimento'],
            },
        ),
        migrations.CreateModel(
            name='TabelaPrecoAcabamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_minima', models.IntegerField(verbose_name='A partir de (unid.)')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Serviço (unid.)')),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabela_precos', to='materiais.acabamento')),
            ],
            options={
                'verbose_name': 'Faixa de Preço',
                'verbose_name_plural': 'Tabela de Preços',
                'ordering': ['qtd_minima'],
            },
        ),
        migrations.CreateModel(
            name='TabelaPrecoPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_minima', models.IntegerField(help_text='Quantidade mínima para aplicar este preço', verbose_name='A partir de (unid.)')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda (unid.)')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabela_precos', to='materiais.papel')),
            ],
            options={
                'verbose_name': 'Faixa de Preço',
                'verbose_name_plural': 'Tabela de Preços',
                'ordering': ['qtd_minima'],
            },
        ),
    ]
