# Generated by Django 6.0 on 2025-12-24 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100, verbose_name='Razão Social / Nome')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='Pessoa de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('segmento', models.CharField(choices=[('PAPEL', 'Papéis e Adesivos'), ('INSUMO', 'Insumos e Acabamentos'), ('IMPRESSORA', 'Tonners e Suprimentos')], default='PAPEL', help_text='Define onde este fornecedor aparecerá nas listas de seleção.', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Cadastros: Fornecedores',
                'ordering': ['nome_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Couchê, Offset, Adesivo', max_length=100)),
                ('gramatura', models.CharField(help_text='Ex: 90g, 150g', max_length=20)),
                ('tipo', models.CharField(blank=True, help_text='Ex: Fosco, Brilho', max_length=50, null=True)),
                ('largura_mm', models.IntegerField(help_text='Ex: 330', verbose_name='Largura (mm)')),
                ('altura_mm', models.IntegerField(help_text='Ex: 480', verbose_name='Altura (mm)')),
                ('estoque_atual', models.IntegerField(default=0, editable=False, verbose_name='Estoque (Pcts)')),
                ('ultimo_valor_pacote', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Último Pago (Pacote)')),
                ('ultimo_preco_unitario', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10, verbose_name='Preço Atual (Folha)')),
            ],
            options={
                'verbose_name': 'Catálogo: Papel',
                'verbose_name_plural': 'Catálogo: Papéis',
                'ordering': ['nome', 'gramatura'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ESPIRAL', 'Espiral'), ('WIREO', 'Wire-o'), ('CAPA', 'Capa (Acetato/PP)'), ('PAPELAO', 'Papelão (Capa Dura)'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('qtd_embalagem', models.IntegerField(verbose_name='Qtd. na Embalagem')),
                ('valor_pacote', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pacote')),
                ('valor_unitario', models.DecimalField(decimal_places=4, editable=False, max_digits=10)),
                ('fornecedor', models.ForeignKey(blank=True, limit_choices_to={'segmento__in': ['INSUMO', 'AMBOS']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.fornecedor')),
            ],
            options={
                'verbose_name': 'Catálogo: Insumo',
                'verbose_name_plural': 'Catálogo: Insumos',
            },
        ),
        migrations.CreateModel(
            name='CompraPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField()),
                ('qtd_pacotes_compra', models.IntegerField(default=1, verbose_name='Qtd. Pacotes')),
                ('qtd_embalagem', models.IntegerField(verbose_name='Folhas por Pacote')),
                ('valor_pacote', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Pacote')),
                ('valor_unitario', models.DecimalField(decimal_places=4, editable=False, max_digits=10)),
                ('fornecedor', models.ForeignKey(limit_choices_to={'segmento__in': ['PAPEL', 'IMPRESSORA']}, on_delete=django.db.models.deletion.PROTECT, to='materiais.fornecedor')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='materiais.papel')),
            ],
            options={
                'verbose_name': 'Movimento: Compra de Papel',
                'verbose_name_plural': 'Movimento: Compras de Papel',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('qtd_pacotes_baixa', models.IntegerField(verbose_name='Qtd. Pacotes Usados')),
                ('observacao', models.CharField(blank=True, max_length=100, verbose_name='Motivo/Obs')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='materiais.papel')),
                ('usuario', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento: Baixa',
                'verbose_name_plural': 'Movimento: Baixas / Uso Interno',
                'ordering': ['-data_movimento'],
            },
        ),
    ]
