"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from django.urls import reverse_lazy
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@cus!xsa5d+3ms^-ui!#yzlxg)_4%)w%oi74t&@2)nh!xsjzp^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.humanize",
    "materiais",
    "orcamentos",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "core/static",
]

UNFOLD = {
    "SITE_TITLE": "Print IA | Sistema Gráfico",
    "SITE_HEADER": "Gestão Print IA",
    "SITE_SYMBOL": "print", # Ícone do logo (pode ser 'speed', 'print', etc)
    
    # Cores personalizadas (Opcional - deixe padrão se preferir)
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "500": "168 85 247", # Roxo padrão Unfold
            "600": "147 51 234",
            "900": "88 28 135",
        },
    },

    # CONFIGURAÇÃO DO MENU LATERAL
    "SIDEBAR": {
        "show_search": True, # Mostra barra de busca no menu
        "show_all_applications": False, # Esconde a lista padrão bagunçada
        "navigation": [
            {
                "title": "Navegação",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "Catálogos",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Papéis",
                        "icon": "description",
                        "link": reverse_lazy("admin:materiais_papel_changelist"),
                    },
                    {
                        "title": "Insumos (Custo)",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:materiais_insumo_changelist"),
                    },
                    {
                        "title": "Acabamentos (Serviços)",
                        "icon": "handyman",
                        "link": reverse_lazy("admin:materiais_acabamento_changelist"),
                    },
                    {   # NOVO
                        "title": "Impressoras e Ativos",
                        "icon": "print",
                        "link": reverse_lazy("admin:materiais_impressora_changelist"),
                    },
                     {   # NOVO (Opcional, se quiser ver a lista solta de peças)
                        "title": "Peças e Suprimentos",
                        "icon": "build_circle",
                        "link": reverse_lazy("admin:materiais_componenteimpressora_changelist"),
                    },
                    {
                        "title": "Fornecedores",
                        "icon": "storefront",
                        "link": reverse_lazy("admin:materiais_fornecedor_changelist"),
                    },
                ],
            },
            {
                "title": "Movimentações",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Compras Papel",
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:materiais_comprapapel_changelist"),
                    },
                    {
                        "title": "Compras Insumo",
                        "icon": "add_shopping_cart",
                        "link": reverse_lazy("admin:materiais_comprainsumo_changelist"),
                    },
                    {   # NOVO
                        "title": "Trocas de Suprimentos",
                        "icon": "published_with_changes",
                        "link": reverse_lazy("admin:materiais_trocasuprimento_changelist"),
                    },
                    {
                        "title": "Baixas de Papel",
                        "icon": "outbox",
                        "link": reverse_lazy("admin:materiais_saidaestoque_changelist"),
                    },
                ],
            },
            {   # NOVA SEÇÃO
                "title": "Relatórios e Leituras",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Leituras de Impressoras",
                        "icon": "speed", 
                        "link": reverse_lazy("admin:materiais_leituraimpressora_changelist"),
                    },
                ],
            },
            {
                "title": "Configurações",
                "separator": True,
                "collapsible": True,
                "items": [
                     {
                        "title": "Tags de Insumos",
                        "icon": "label",
                        "link": reverse_lazy("admin:materiais_categoriainsumo_changelist"),
                    },
                    {
                        "title": "Tags de Acabamentos",
                        "icon": "label",
                        "link": reverse_lazy("admin:materiais_categoriaacabamento_changelist"),
                    },
                    {
                        "title": "Usuários e Acessos",
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ]
             }
        ],
    },
}

# Configuração de Login
# Avisa ao Django para usar a tela do Admin quando precisar autenticar
LOGIN_URL = '/admin/login/'

# Para onde ir depois de logar (opcional, mas útil)
LOGIN_REDIRECT_URL = '/orcamentos/novo/'