# Generated by Django 6.0 on 2025-12-27 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome / Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, null=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone/Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato', models.CharField(blank=True, help_text='Nome de quem pediu o orçamento (para PJ)', max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Cartão de Visita, Catálogo, Folder', max_length=100)),
                ('quantidade', models.IntegerField(default=100)),
                ('largura_final_mm', models.IntegerField(verbose_name='Largura Final (mm)')),
                ('altura_final_mm', models.IntegerField(verbose_name='Altura Final (mm)')),
                ('sangria_mm', models.IntegerField(default=3, verbose_name='Sangria (mm)')),
                ('capacidade_corte_folhas', models.IntegerField(default=250, help_text='Quantas folhas a guilhotina corta por vez (maço)?')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_consumida', models.DecimalField(decimal_places=4, help_text='Qtd total consumida no pedido', max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiais.insumo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='orcamentos.itemorcamento')),
            ],
        ),
        migrations.CreateModel(
            name='AcabamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Quantidade a aplicar (geralmente igual à tiragem)')),
                ('observacao', models.CharField(blank=True, max_length=100)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiais.acabamento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acabamentos', to='orcamentos.itemorcamento')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('validade_dias', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em Análise / Rascunho'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='EM_ANALISE', max_length=20)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete/Entrega')),
                ('percentual_imposto', models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Imposto (%)')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Comissão (%)')),
                ('percentual_cartao', models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Taxa Cartão (%)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='orcamentos.cliente')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamento'),
        ),
        migrations.CreateModel(
            name='ParteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parte', models.CharField(default='Corpo', help_text='Ex: Capa, Miolo, Encarte', max_length=50)),
                ('paginas', models.IntegerField(default=1, verbose_name='Nº Páginas/Lâminas')),
                ('cor_impressao', models.CharField(choices=[('4x4', 'Colorido Frente e Verso'), ('4x0', 'Colorido Somente Frente'), ('1x1', 'Preto Frente e Verso'), ('1x0', 'Preto Somente Frente'), ('0x0', 'Sem Impressão (Apenas Papel)')], default='4x0', max_length=3)),
                ('formato_papel_usado', models.CharField(editable=False, max_length=50)),
                ('itens_por_folha', models.IntegerField(default=0, verbose_name='Aproveitamento (un/fl)')),
                ('margem_papel_top', models.IntegerField(default=5, verbose_name='Margem Topo (mm)')),
                ('margem_papel_bottom', models.IntegerField(default=5, verbose_name='Margem Base (mm)')),
                ('margem_papel_left', models.IntegerField(default=5, verbose_name='Margem Esq (mm)')),
                ('margem_papel_right', models.IntegerField(default=5, verbose_name='Margem Dir (mm)')),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiais.impressora')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='orcamentos.itemorcamento')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiais.papel')),
            ],
        ),
    ]
