# Generated by Django 6.0 on 2025-12-29 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome / Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, null=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone/Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imposto_padrao', models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Imposto Padrão (%)')),
                ('comissao_padrao', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Comissão Padrão (%)')),
                ('taxa_cartao', models.DecimalField(decimal_places=2, default=4.5, max_digits=5, verbose_name='Taxa Cartão (%)')),
                ('custo_hora_arte', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Custo Hora Arte (R$)')),
                ('logo_empresa', models.ImageField(blank=True, null=True, upload_to='config/')),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Cartão de Visita, Folder', max_length=100)),
                ('largura_final_mm', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Largura (mm)')),
                ('altura_final_mm', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Altura (mm)')),
                ('sangria_mm', models.DecimalField(decimal_places=1, default=3, max_digits=4, verbose_name='Sangria (mm)')),
                ('cor_impressao', models.CharField(default='4x0', help_text='Ex: 4x0, 4x4, 1x0', max_length=10, verbose_name='Cores')),
                ('paginas', models.IntegerField(default=1, verbose_name='Nº Páginas/Lâminas')),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiais.impressora', verbose_name='Máquina')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiais.papel', verbose_name='Papel / Mídia')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrcamentoTiragem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade / Tiragem')),
                ('custo_papel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_impressao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_acabamento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_total_producao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_final_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiragens', to='orcamentos.itemorcamento')),
            ],
            options={
                'ordering': ['quantidade'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='EM_ANALISE', max_length=20)),
                ('percentual_imposto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentual_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentual_cartao', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='orcamentos.cliente')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamento'),
        ),
        migrations.CreateModel(
            name='ProdutoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Cartão de Visita Padrão', max_length=100, verbose_name='Nome do Modelo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Interna')),
                ('largura_final_mm', models.IntegerField(verbose_name='Largura (mm)')),
                ('altura_final_mm', models.IntegerField(verbose_name='Altura (mm)')),
                ('sangria_mm', models.IntegerField(default=3, verbose_name='Sangria (mm)')),
                ('impressora_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.impressora')),
                ('papel_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.papel')),
            ],
            options={
                'verbose_name': 'Modelo de Produto',
                'verbose_name_plural': 'Modelos de Produtos',
            },
        ),
    ]
